<?php

/**
 * 实现钩子hook_perm().
 */
 
function dhg_pingfen_permission(){
	return array(
	  'dhg pingfen' => array(
      'title' => t('Dhg pingfen'),
		),
	);
}

/**
 * 实现钩子hook_node_view().
 */
 
function dhg_pingfen_node_view($node, $view_mode, $langcode){
  //if($node->type == "bookreview" && user_access('dhg pingfen')){
	if($node->type == "bookreview" && user_access('dhg pingfen')){
	  
		$node->content['duhougan_pingfen_display'] = array(
			//'#markup' => theme('dhg_pingfen',$node), 
			//'#markup' => '123456', 
			'#weight' => 10, 
			'#theme' => 'dhg_pingfen',
			'#node' => $node,
			//'#value' => theme('dhg_pingfen', $node),
		);
		
		//$node->content['dhg_pingfen_rate_form'] =  theme('dhg_pingfen',$node);
		//$node->content['dhg_pingfen_rate_form'] =  "theme('dhg_pingfen',node)";
  }
}



/**
 * 实现钩子hook_node_load().
 */
 /*
function dhg_pingfen_node_load($nodes, $types) {
  if(!in_array('bookreview',$types)){
	  return;
	}
	foreach ($nodes as $nid => $node) {
	  if($node->type == "bookreview" && user_access('dhg pingfen')){
	    $nodes[$nid]->rateform = theme('dhg_pingfen',$node);
		}
  }
}*/


/**
 * 实现钩子 hook_theme().
 */
 
function dhg_pingfen_theme() {
  return array(
    'dhg_pingfen' => array(
      'variables' => array('node' => NULL),
			'file' => 'dhg_pingfen.pages.inc',
    ),
  );
}

/**
 * 实现钩子 hook_forms().
 *
 * Register an "dhg_pingfen_rate_form" form for each node to prevent id collisions.
 */
function dhg_pingfen_forms($form_id, $args) {
  $forms = array();
  if (is_object($args[0]) && isset($args[0]->type)) {
    $node = $args[0];
    if ($node->type =='bookreview') {
      $forms['dhg_pingfen_rate_form_'. $node->nid] = array('callback' => 'dhg_pingfen_rate_form');
    //  $forms['uc_catalog_buy_it_now_form_'. $product->nid] = array('callback' => 'uc_catalog_buy_it_now_form');
    }
  }
  return $forms;
}
