<?php

/* ccec报名助手，生成准考证，默认下个报名继承上个报名的级别信息；
 * 
 */

function apply_assit_menu() {
	
	$items ['test'] = array ('title' => 'test', 'description' => t ( 'test' ), 'page callback' => 'apply_assit_show_profile', 'access callback' => true );
	
	return $items;

}

function apply_assit_show_profile() {
	global $user;
	$myprofile = profile2_load_by_user ( $user, 'agent_profile' );
	$agent_code = $myprofile->field_code ['und'] [0] ['value'];
	
	$sql = "select field_candidate_id_value from  field_data_field_candidate_id where entity_id=(select max(nid) from node where type='baoming' and uid=:uid)";
	
	$result = db_query ( $sql, array (':uid' => $user->uid ) );
	$record = $result->fetchObject ();
	$candidate_id = $record->field_candidate_id_value;
	
	if (empty ( $candidate_id )) {
		$candidate_id = $agent_code . '0001';
	} else {
		$candidate_index = substr ( $candidate_id, 5, 4 ) + 1;
		$candidate_index_length = strlen ( $candidate_index );
		$candidate_index_add_length = 4 - $candidate_index_length;
		
		$candidate_id = $agent_code . str_repeat ( '0', $candidate_index_add_length ) . $candidate_index;
	}
	
	return t ( $candidate_id );

}

function apply_assit_node_presave($node) {
	global $user;
	
	$node_type = 'baoming';
	$candidate_id_suffix_length = 4; 
	
	if ($node->type == "baoming") {
		if (! isset ( $node->field_candidate_id ['zh-hans'] [0] ['value'] )) {
			
			$myprofile = profile2_load_by_user ( $user, 'agent_profile' );
			
			$agent_code = $myprofile->field_code ['und'] [0] ['value'];
			
			$sql = "select field_candidate_id_value from  field_data_field_candidate_id where entity_id=(select max(nid) from node where type=:node_type and uid=:uid)";
			
			$result = db_query ( $sql, array (':uid' => $user->uid,':node_type' => $node_type ) );
			$record = $result->fetchObject ();
			$candidate_id = @$record->field_candidate_id_value;
			
			//当去的的上一个最大准考号（candidate_id）为空时，准考号=报名点编码($agent_code)+（补位长度-1）位数的0+1；否则取出值后+1
			if (empty ( $candidate_id )) {
				$candidate_id = $agent_code . str_repeat ( '0', $candidate_id_suffix_length-1 ).'1';
			} else {
				$candidate_index = substr ( $candidate_id, strlen($agent_code), $candidate_id_suffix_length ) + 1;
				$candidate_index_length = strlen ( $candidate_index );
				$candidate_index_add_length = $candidate_id_suffix_length - $candidate_index_length;
				
				$candidate_id = $agent_code . str_repeat ( '0', $candidate_index_add_length ) . $candidate_index;
			}
			
			$node->field_candidate_id ['zh-hans'] [0] ['value'] = $candidate_id;
		}
	
	}

}