<?php

/* ccec报名助手，生成准考证，默认下个报名继承上个报名的级别信息；
 * 
 */

function apply_assit_menu(){

     $items['test'] = array(
       'title' =>'test',
       'description' => t('test'),
       'page callback' => 'apply_assit_show_profile',
       'access callback' =>true,   
     );
     
   	
      return $items;  


}

function apply_assit_show_profile()
{
	global $user;
	$myprofile = profile2_load_by_user($user, 'agent_profile');
    print_r($myprofile);
	return t($user->uid);
	
}

function apply_assit_node_presave($node){
	global $user;
	
	if($node->type == "baoming"){
		if(!isset($node->field_candidate_id['zh-hans'][0]['value'])){		
	        			
			$myprofile = profile2_load_by_user($user, 'agent_profile');
			
			//print_r($myprofile);
			
			$node->field_candidate_id['zh-hans'][0]['value']='22222222222';	
		}

		
	}


}