<?php

/* 俄语等级考试报名助手，用来限制报名数；
 * 
 */

//function apply_assit_menu() {
	
	//$items ['test'] = array ('title' => 'test', 'description' => t ( 'test' ), 'page callback' => 'apply_assit_show_profile', 'access callback' => true );
	
	//return $items;

//}

//function apply_assit_show_profile() {
	//global $user;
	//$uid = $user->uid;

	//$profile_type = 'main';
	//$node_type = 'baoming';
		
  //$query = new EntityFieldQuery();		
  //$publicGroupCount = $query
	  //->entityCondition('entity_type', 'node')
		//->entityCondition('bundle', 'baoming')
		//->fieldCondition('field_group','value','公共英语组')
		//->propertyCondition('uid',$uid)
    //->count()
    //->execute();

	//return t ( $publicGroupCount );

//}


function apply_assit_form_alter(&$form, &$form_state, $form_id){		
	if ($form_id == 'baoming_node_form') {
		$form ['#validate'] [] = 'apply_assit_extra_validate';
	}
}


function apply_assit_extra_validate($form, &$form_state) {
		global $user;
		$uid = $user->uid;

		$baomingLimited =1;

		  $query = new EntityFieldQuery();				   
		  $baomingCount = $query
			  ->entityCondition('entity_type', 'node')
				->entityCondition('bundle', 'baoming')
				->propertyCondition('uid',$uid)
			->count()
			->execute();


		if(strtolower (arg(2))!='edit'){
			if($baomingCount>=$baomingLimited){
					form_set_error ( 'field_firstname',t ( '报名数超出限制。每名报名者只能进行一次报名'));
			  }
		}


}




