<?php

/**
 * Implements hook_menu().
 */
function testoracle_menu() {
  $items = array();
	$items['testoracle'] = array(
    'title' => 'Test oracle',
    'description' => 'Test oracle.',
    'page callback' => 'testoracle_test_page',
    'access callback' => TRUE,
  );
	return $items;
}
function testoracle_test_page4(){
$output ="1234";
$node = node_load(7907);
debug($node);


Database::getConnection('default', 'data')->query('set names latin1');
	$query = Database::getConnection('default', 'data')
	  ->select('books', 'b')
		->fields('b', array('bsno', 'zjml', 'sp', 'nrty', 'jcpd', 'zzjj', 'features', 'authorizationdetails', 'relativeinfo'))
		->condition('b.bsno', 1000, '<')
		//->condition('b.bsno', $context['sandbox']['last_bsno'], '=')
		->orderBy('b.bsno', 'ASC')
		->range(0, 10);
	 
	$result = $query->execute();
 // drupal_set_message('123456');
	foreach ($result as $record) { 
	  //得到nid
		$nid_query = db_select('field_data_field_bsno', 'fb')
			->fields('fb', array('entity_id'))
			->condition('fb.field_bsno_value', $record->bsno, '=')
			->condition('fb.bundle', 'book', '=');
			
		$nid_result = $nid_query->execute()->fetchAssoc();
		$nid = $nid_result['entity_id'];
		//得到节点
    $node = node_load($nid);
		
		 //drupal_set_message('123456789');
		//编码转换
		$record->zjml = iconv('EUC-CN',"UTF-8//IGNORE",$record->zjml) ; //iconv转换
		$record->sp = iconv('EUC-CN',"UTF-8//IGNORE",$record->sp) ; //iconv转换
		
		$record->nrty = iconv('EUC-CN',"UTF-8//IGNORE",$record->nrty) ; //iconv转换
		$record->jcpd = iconv('EUC-CN',"UTF-8//IGNORE",$record->jcpd) ; //iconv转换
		$record->zzjj = iconv('EUC-CN',"UTF-8//IGNORE",$record->zzjj) ; //iconv转换
		$record->features = iconv('EUC-CN',"UTF-8//IGNORE",$record->features) ; //iconv转换
		
		$record->authorizationdetails = iconv('EUC-CN',"UTF-8//IGNORE",$record->authorizationdetails) ; //iconv转换
		$record->relativeinfo = iconv('EUC-CN',"UTF-8//IGNORE",$record->relativeinfo) ; //iconv转换

		
		//向node映射
    //$this->addFieldMapping('field_directory', 'zjml');
		if(empty($node->field_directory['und'][0]['value']) && !empty($record->zjml)){
		  $node->field_directory = array(
				'und' => array(
					0 => array(
						'value' => $record->zjml,
						'format' => 'full_html',
					)
				)
			);
			//$node->field_directory['und'][0]['value'] = $record->zjml;
		}
		//$this->addFieldMapping('field_sp', 'sp');
		if(empty($node->field_sp['und'][0]['value']) && !empty($record->sp)){
		  $node->field_sp = array(
				'und' => array(
					0 => array(
						'value' => $record->sp,
						'format' => 'full_html',
					)
				)
			);
		}
		//$this->addFieldMapping('body', 'nrty')
		if(empty($node->body['und'][0]['value']) && !empty($record->nrty)){
		  $node->body = array(
				'und' => array(
					0 => array(
						'value' => $record->nrty,
					//	'summary' => substr($record->nrty, 0, 200),
						'format' => 'full_html',
					)
				)
			);
		}
		//$this->addFieldMapping('field_sample', 'jcpd');
		if(empty($node->field_sample['und'][0]['value']) && !empty($record->jcpd)){
		  $node->field_sample = array(
				'und' => array(
					0 => array(
						'value' => $record->jcpd,
						'format' => 'full_html',
					)
				)
			);
		}
		//$this->addFieldMapping('field_author_info', 'zzjj');
		if(empty($node->field_author_info['und'][0]['value']) && !empty($record->zzjj)){
		  $node->field_author_info = array(
				'und' => array(
					0 => array(
						'value' => $record->zzjj,
						'format' => 'full_html',
					)
				)
			);
		}
		//$this->addFieldMapping('field_features', 'features');
    if(empty($node->field_features['und'][0]['value']) && !empty($record->features)){
		  $node->field_features = array(
				'und' => array(
					0 => array(
						'value' => $record->features,
						'format' => 'full_html',
					)
				)
			);
		}		
		//$this->addFieldMapping('field_authorization_details', 'authorizationdetails');
		if(empty($node->field_authorization_details['und'][0]['value']) && !empty($record->authorizationdetails)){
		  $node->field_authorization_details = array(
				'und' => array(
					0 => array(
						'value' => $record->authorizationdetails,
						'format' => 'full_html',
					)
				)
			);
		}		
		//$this->addFieldMapping('field_relative_info', 'relativeinfo');
		if(empty($node->field_relative_info['und'][0]['value']) && !empty($record->relativeinfo)){
		  $node->field_relative_info = array(
				'und' => array(
					0 => array(
						'value' => $record->relativeinfo,
						'format' => 'full_html',
					)
				)
			);
		}	
    if($node->nid > 0){		
      //node_save($node);
		}
		
	  //$context['sandbox']['progress']++;
	  //$context['sandbox']['last_bsno'] = $record->bsno;
	}



return $output;
}

function testoracle_test_page(){
   $output = "123456";

	/*

  Database::getConnection('default', 'data1')->query('set names latin1');
		$query = Database::getConnection('default', 'data1')
		->select('qrybooks', 'q')
    ->fields('q', array('bsno', 'bname', 'ebname', 'materielno', 'isbn', 'writer', 'bianshi', 'yc', 'price', 'zs',
		   'ys', 'publishdate', 'inputdate', 'zdfs', 'kb', 'ekb', 'type', 'dzdx'))
	  //->leftJoin('term_hierarchy', 'th', 'td.tid = th.tid')
		//->leftJoin('term_data', 'tdp', 'th.parent = tdp.tid')
		//->addField('tdp', 'name', 'parent_name')
		->condition('q.bsno', 100000, '<');
		//->execute();
	$result = $query->execute();
	foreach($result as $row){
	  $encode = mb_detect_encoding($row->bname);
		 $output .= $encode;
	  //$row->bname = iconv('UTF-8',"latin1", $row->bname); //icon
		//$row->bname = iconv("",'UTF-8//IGNORE', $row->bname); //icon
		$row->bname = iconv('EUC-CN',"UTF-8//IGNORE",$row->bname) ; //iconv转换
	  $output .= $row->bname;

	}
	*/
	  $nid = 11157;
		$node = node_load($nid);
		//if($node->changed > time()-1*24*60*60){
		//if($node->nid > 10777){
		//drupal_set_message('nid:'. $nid);
		//drupal_set_message("node->field_bianshi['und'][0]['value']". $node->field_bianshi['und'][0]['value']);
		//ebug($record);
		//drupal_set_message('node1->field_bianshi:'. $node1->field_bianshi['und'][0]['tid']);
		$bianshi_term = taxonomy_term_load($node->field_bianshi['und'][0]['tid']);
		//drupal_set_message('bianshi_term->name'. $bianshi_term->name);
		$tname = '';
		//if(!empty(strstr($bianshi_term->name,'综合语种'))){
		//$tname = '综合语种出版分社';
		
		drupal_set_message("123456789:".$bianshi_term->name);
		$output .= strstr($bianshi_term->name,'少儿出版');

		if(fltrp_qy_str_contain($bianshi_term->name,'综合语种')){
		drupal_set_message("123456789");
		  $tname = '综合语种出版分社';
			
		}
		//if(!empty(strstr($bianshi_term->name,'汉语'))){
		if(fltrp_qy_str_contain($bianshi_term->name,'汉语')){
		  drupal_set_message("123456");
		  drupal_set_message("123456");
		  $tname = '汉语出版分社';
			
		}
		if(fltrp_qy_str_contain($bianshi_term->name,'儿童出版') || fltrp_qy_str_contain($bianshi_term->name,'少儿出版') ){
		  $tname = '少儿出版分社';
			drupal_set_message("000123456");
			
		}
	$output .= ": ".$tname;
	return $output;
}