<?php

/**
 * Implements hook_menu().
 */
function testoracle_menu() {
  $items = array();
	$items['testoracle'] = array(
    'title' => 'Test oracle',
    'description' => 'Test oracle.',
    'page callback' => 'testoracle_test_page',
    'access callback' => TRUE,
  );
	return $items;
}

function testoracle_test_page(){
$output ="1234";
	
	
	Database::getConnection('default', 'data')->query('set names latin1');
	$query = Database::getConnection('default', 'data')
	  ->select('bookotype', 'b')
		->fields('b', array('id', 'name', 'brief', 'isseries'))
		->condition('b.isseries', 1, '=')
		//->condition('b.flag', 1, '<')
		->condition('b.id', 'YYZZSW', '=')
		//->condition('q.bsno', 1000, '<')
		->range(0, 10);
	
	$result = $query->execute();
	//drupal_set_message('tname:12233455');
	foreach ($result as $record) { 
	  $encode = mb_detect_encoding($record->name, array("ASCII","GB2312","GBK","UTF-8","BIG5"));
		drupal_set_message('encode:'.$encode);
	  if($record->id =='YYZZSW'){
		  drupal_set_message($record->name);
			drupal_set_message($record->brief);
		}
	  $record->name = iconv('EUC-CN',"UTF-8//IGNORE",$record->name) ; //iconv转换
		$record->brief = iconv('EUC-CN',"UTF-8//IGNORE",$record->brief) ; //iconv转换
		if($record->id =='YYZZSW'){
		  drupal_set_message('name:'.$record->name);
			drupal_set_message('brief:'.$record->brief);
		}
		
		$term = new stdClass();
	  $term->vid = 16;
	  $term->name = trim($record->name);
		$term->description = trim($record->brief);
		
		$tid_query = db_select('field_data_field_oid', 'f')
			->fields('f', array('entity_id'))
			->condition('f.field_oid_value', $record->id, '=')
			->condition('f.entity_type', 'taxonomy_term', '=');
			
		$tid_result = $tid_query->execute()->fetchAssoc();
		$tid = $tid_result['entity_id'];
		if(!empty($tid)){
		  $term->tid = $tid;
		}
		//$term->description = trim($record->brief);
		$term->field_oid = array(
				'und' => array(
					0 => array(
						'value' => $record->id,
					)
				)
		);
	  $status = taxonomy_term_save($term);
			

	}





return $output;
}


function testoracle_test_page4(){
$output ="1234";
$nid_query = db_select('field_data_field_bsno', 'fb')
			->fields('fb', array('entity_id'))
			->condition('fb.field_bsno_value', 529, '=')
			->condition('fb.bundle', 'book', '=');
			
		$nid_result = $nid_query->execute()->fetchAssoc();
		$nid = $nid_result['entity_id'];
		//得到节点
    $node = node_load($nid);
		
		debug($node);
		//drupal_set_message("123:".$record->bsno.";456:".$nid);
		
		//根据cid得到tid
		$tid_query = db_select('field_data_field_oid', 'f')
			->fields('f', array('entity_id'))
			->condition('f.field_oid_value', 'YYZHGN', '=')
			->condition('f.entity_type', 'taxonomy_term', '=');
			
		$tid_result = $tid_query->execute()->fetchAssoc();
		$tid = $tid_result['entity_id'];
		$output .="tid:".$tid;
return $output;
}
function testoracle_test_page3(){
$output ="1234";
//$nid = 1;
//$node = node_load($nid);

//$tid = 202;
	//$term = taxonomy_term_load($tid);

//debug($term);

/*
$max = Database::getConnection('default', 'data')
			->select('book2type', 'b')
			//->condition('b.cid', $fenshe_array, 'IN')
			->leftJoin('bookotype', 'bt', 'b.cid = bt.id AND bt.isseries = :isseries', array(':isseries' => 1))
			->condition('b.flag', 1, '<')
			//->leftJoin('bookotype', 'bt', 'b.cid = bt.id AND bt.isseries = :isseries', array(':isseries' => 1))
			->countQuery()
			->execute()
			->fetchField();
	*/		
  $max_sql = "select count(*) 
	         from book2type b 
					 LEFT JOIN bookotype bt ON b.cid = bt.id 
					 WHERE b.flag < 1 AND bt.isseries = :isseries";
	$result = Database::getConnection('default', 'data')->query($max_sql, array(':isseries' => 1));
	$max = $result->fetchField();
$output .= $max;
return $output;
}
function testoracle_test_page2(){
  $output ="1234";
  $size =99;
	//$vid = 8;
	//$types_str ='story,page';
	//$types_str = "'".implode("','", $types)."'";
	if(!isset($context['sandbox']['progress'])){
		$context['sandbox']['progress'] = 0;
		$context['sandbox']['max'] = Database::getConnection('default', 'data')
			->select('book2type', 'b')
			->countQuery()
			->execute()
			->fetchField();
		$output .= $context['sandbox']['max'];
	}
	$query = Database::getConnection('default', 'data')
	  ->select('book2type', 'b')
		->fields('b', array('bsno', 'cid'))
		->condition('b.flag', 1, '<')
		//->condition('q.bsno', 1000, '<')
		->range(0, $size);
	
	$result = $query->execute();
	foreach ($result as $record) { 
	//$record->cid ='BMJC';
	
	  //debug($record);
    $tname = '';	
		$output .= $record->cid;
		
	  if($record->cid =='BMJC'){
		  $tname = '基础英语教育分社';
		}
		if($record->cid =='BMZJ'){
		  $tname = '职业教育出版分社';
		}
		if($record->cid =='BMGY'){
		  $tname = '高等英语教育出版分社';
		}
		if($record->cid =='BMZY'){
		  $tname = '英语教育出版分社';
		}
		if($record->cid =='BMXS'){
		  $tname = '综合英语出版分社';
		}
		if($record->cid =='BMSK'){
		  $tname = '人文社科出版分社';
		}

		if($record->cid =='BMEL'){
		  $tname = '《英语学习》杂志社';
		}
		if($record->cid =='BMSM'){
		  $tname = '数码产品事业部';
		}
		if($record->cid =='BMWL'){
		  $tname = '电子网络出版分社';
		}
		if($record->cid =='BMPG'){
		  $tname = '北京青苹果文化发展公司';
		}
		if($record->cid =='BMEF'){
		  $tname = '早教中心';
		}
		
		if(!empty($tname)){
		
		  //根据machine_name得到vid,
		  $vid_result = db_select('taxonomy_vocabulary', 'tv')
			->fields('tv', array('vid'))
			->condition('tv.machine_name', 'fenshe', '=')
			->execute()
			->fetchAssoc();
			
			$vid = $vid_result['vid'];
			
		  $tid = fltrp_qy_get_tid_by_name($tname, $vid);
			$output .= 'tid:'.$tid;
			$output .= 'tid:'.$tname;
			//根据bsno得到nid
			$nid_query = db_select('field_data_field_bsno', 'fb')
			->fields('fb', array('entity_id'))
			->condition('fb.field_bsno_value', $record->bsno, '=')
			->condition('fb.bundle', 'book', '=');
			
			$nid_result = $nid_query->execute()->fetchAssoc();
			$nid = $nid_result['entity_id'];
			$output .= $nid;
			$node = node_load($nid);
			
			$node->field_department = array(
				'und' => array(
					0 => array(
						'tid' => $tid
					)
				)
			);
			debug($node);
			node_save($node);
		}
		drupal_set_message('bsno:'.$record->bsno.';cid:'.$record->cid);
		
	  Database::getConnection('default', 'data')
		  ->update('book2type')
			->fields(
			   array(    
					 'flag' => 1,    
				 ))
			->condition('bsno', $record->bsno, '=')
			->condition('cid', $record->cid, '=')
			->execute();
			
	 // $context['sandbox']['progress']++;
	
		
	}
  return $output;
}
function testoracle_test_page1(){
   $output = "123456";
	 
	// $query = Database::getConnection('default', 'sqlsrv');
	//->select('qrybooks', 'n')
    //->fields('n', array('nid'))
	//->condition('n.type', 'zuowen_ziyou_shangchuan', '=')
	//->range(0, 10);
	/*
	$result = $query->execute();
	foreach ($result as $record) { 
	  $output .= 'test:'. $record->nid;
	}
	*/
	/*
	$path = '';
	$path=drupal_get_path('module', 'migrate_fltrp');
	$path=$path.'/bookext/'.'443'.'b.txt';
	$data = file_get_contents($path) ;
	//$encode = mb_detect_encoding($data, array("ASCII","latin1","GB2312","GBK","UTF-8","BIG5"));
  $encode = mb_detect_encoding($data);
	$output .= 'encode:'.$encode;
	$data = iconv('',"UTF-8//IGNORE",$data); //icon
	$output .= $data;
	*/
	
	$query = Database::getConnection('default', 'drupal74')
		->select('qrybooks', 'q')
    ->fields('q', array('bsno', 'bname', 'ebname', 'materielno', 'isbn', 'writer', 'bianshi', 'yc', 'price', 'zs',
		   'ys', 'publishdate', 'inputdate', 'zdfs', 'kb', 'ekb', 'type', 'dzdx'))

		->condition('q.bsno', 500, '<');
	//$result = $query->execute();
	
	db_set_active('drupal74');
	db_query('set names latin1');
	$result = db_query('select dzdx from qrybooks where bsno < 1000');
	foreach($result as $row){
	  $encode = mb_detect_encoding($row->dzdx);
		 $output .= $encode;
	  //$row->bname = iconv('UTF-8',"latin1", $row->bname); //icon
		$row->dzdx = iconv("",'UTF-8//IGNORE', $row->dzdx); //icon
	  $output .= $row->dzdx;
	}
	db_set_active('default');
	
/*
  Database::getConnection('default', 'data')->query('set names latin1');
		$query = Database::getConnection('default', 'data')
		->select('qrybooks', 'q')
    ->fields('q', array('bsno', 'bname', 'ebname', 'materielno', 'isbn', 'writer', 'bianshi', 'yc', 'price', 'zs',
		   'ys', 'publishdate', 'inputdate', 'zdfs', 'kb', 'ekb', 'type', 'dzdx'))
	  //->leftJoin('term_hierarchy', 'th', 'td.tid = th.tid')
		//->leftJoin('term_data', 'tdp', 'th.parent = tdp.tid')
		//->addField('tdp', 'name', 'parent_name')
		->condition('q.bsno', 1000, '<');
		//->execute();
	$result = $query->execute();
	foreach($result as $row){
	  //$encode = mb_detect_encoding($row->bname);
		// $output .= $encode;
	  //$row->bname = iconv('UTF-8',"latin1", $row->bname); //icon
		//$row->bname = iconv("",'UTF-8//IGNORE', $row->bname); //icon
	  $output .= $row->dzdx;
	}
	*/
		/*
	Database::getConnection('default', 'data')->query('set names latin1');
		$query = Database::getConnection('default', 'data');
		$query->select('qrybooks', 'q')
    ->fields('q', array('type'))
	  //->leftJoin('term_hierarchy', 'th', 'td.tid = th.tid')
		//->leftJoin('term_data', 'tdp', 'th.parent = tdp.tid')
		//->addField('tdp', 'name', 'parent_name')
		->distinct();
		//->condition('q.dzdx', 1000, '<');
		//->execute();
	$result = $query->execute();
	foreach($result as $row){
	   $output .= $row->type;
	}
	*/
	
	return $output;
}