<?php

$plugin = array(                                                                                                                                             
           'title' => t('middle'),                                                                                                                             
           'theme' => 'middle',                                                                                                                                
           'css' => 'middle.css',                                                                                                                              
           'admin css' => 'middle_admin.css',
           'regions' => array(                                                                                                                               
                      'focus' => t('focus'),                                                                                                         
                      'line_red' => t('line_red'),
                      'news' => t('news'),
                      'line_03' => t('line_03'),
                      'banner_3' => t('banner_3'),
                      'Categories' => t('Categories'),                                                                                                      
            ),                                                                                                                                               
); 
