<?php
// $Id$

/**
 * @file
 * 实现publisher字段的迁移.
 */
 
 /**
 * 实现钩子hook_menu().
 */
function tongbu_menu() {

  $items['admin/config/development/tongbu'] = array(
    'title'            => 'tongbu',
    'page callback'    => 'drupal_get_form',
	  'page arguments'    =>  array('tongbu_tongbu_form'),
    'access arguments' => array('administer site configuration'),
    'weight'           => 1,   
  );
 	
  return $items;
}
function tongbu_tongbu_form(){
	
	$form['submit'] = array(
		'#type' =>'submit',
		'#value' => t('开始同步'),
	);
	/*
	$form['test'] = array(
		'#value' => t('迁移'),
	);
	*/
	return $form;
}

function tongbu_tongbu_form_submit($form,&$form_state){
	//$types = array_filter($form_state['values']['types']);
	$batch =array(
		'operations' => array(
		  array('bookotype_tongbu_process',array()),
		  ),
		'finished' => 'bookotype_tongbu_finished',
		'title' => t('同步旧节点到新节点'),
		'init_message' => t('开始批量同步.'),
		//'progress_message' => t('Reindexed @current out of @total.'),
		'error_message' => t('批量同步遇到错误.'),
	);
	batch_set($batch);
}

function bookotype_tongbu_process(&$context){
	$from_nid = 5041;
  $size = 10;

	if(!isset($context['sandbox']['progress'])){
		$context['sandbox']['progress'] = 0;
		$context['sandbox']['last_nid'] = 0;
		$context['sandbox']['max'] =
      db_select('node', 'n')
			->condition('n.type', 'book')
			->condition('n.nid', $from_nid, '>')
			->countQuery()
			->execute()
			->fetchField();
			
		
	}
	
	$query = db_select('node', 'n')
		->fields('n', array('nid', 'vid', 'title'))
		->condition('n.nid', $context['sandbox']['last_nid'], '>')
		->condition('n.nid', $from_nid, '>')
		->condition('n.type', 'book')
		->orderBy('n.nid', 'ASC')
		->range(0, $size);
		
	$result = $query->execute();
	//drupal_set_message('tname:12233455');
	foreach ($result as $record) { 
	  $nid = $record->nid;
		$node = node_load($nid);
		
		$title = $node->title;

    //查找标题相同的旧节点		
    $query_old = db_select('node', 'n')
			->fields('n', array('nid', 'vid'))
			->condition('n.nid', $from_nid+1, '<')
			->condition('n.title', $title)
			->condition('n.type', 'book');
		
		$old_node = $query_old->execute()->fetchObject();
		
		if(!empty($old_node ) && isset($old_node->nid)){
		  $old_node = node_load($old_node->nid);
			//同步旧节点的属性信息.
			//英文产品分类\物料号\SKU
			$node->field_materielno['und'][0]['value'] = $old_node->field_materielno['und'][0]['value'] ;
			if(!empty($old_node->field_en_fenlei['und'][0]['tid'])){
			  $node->field_en_fenlei['und'][0]['tid'] = $old_node->field_en_fenlei['und'][0]['tid'] ;
			}
			$node->model = $old_node->model;
			node_save($node);
		}
		
		
	  $context['sandbox']['progress']++;
	  $context['sandbox']['last_nid'] = $record->nid;
	}

	if($context['sandbox']['progress'] == $context['sandbox']['max']){
		$context['finished'] = 1;
	}else{
		$context['finished'] = $context['sandbox']['progress']/$context['sandbox']['max'];
	}
		
}

function bookotype_tongbu_finished($success, $results, $operations){
	if ($success) {
		// Here we do something meaningful with the results.
		$message = t('同步数据完成');
		
	}
	else {
		// An error occurred.
		// $operations contains the operations that remained unprocessed.
		$error_operation = reset($operations);
		$message = '在同步数据时出现一个错误'. $error_operation[0] .' 其参数为 :'. print_r($error_operation[0], TRUE);
	}
	drupal_set_message($message);
}

