<?php

$plugin = array(
           'title' => t('frame'),
           //'icon' => 'test.png',
           'theme' => 'frame',
           'css' => 'frame.css',
           //'admin css' => 'quiz_admin.css',
           'regions' => array(
                      'frame_top' => t('frame_top'),
                      'frame_left' => t('frame_left'),
                      'frame_right' => t('frame_right'),
                      'frame_middle' => t('frame_middle'),
            ),
);
