<?php

$plugin = array(                                                                                                                                             
           'title' => t('middle'),                                                                                                                             
           'theme' => 'middle',                                                                                                                                
           'css' => 'middle.css',                                                                                                                              
           'regions' => array(                                                                                                                               
                      'cansaitushu' => t('cansaitushu'),                                                                                                         
                      'youxiu' => t('youxiu'),                                                                                                       
            ),                                                                                                                                               
); 
