<?php

/**
 * @file 
 * 演示 menu api
 *
*/

/* hook_menu */

function menu_abc_menu() {

	$items['menu_abc] = array(
		'title'=> '老葛教我编写drupal',
		'description' => '这里是描述_menu',
		'page_callback' => 'menu_abc_callback_page',
		'access control' => TURE,
		'menu_name' => 'main_menu',)；

	return $items;

}

/* callback */

function menu_abc_callback_page() {
	$render_array = array();
	$render_array['#markup'] = t('菜单abc的内容在#markup中定义');

	return $render_array;
}
