<?php

$plugin = array(
           'title' => t('right'),
           'theme' => 'right',
           'css' => 'right.css',
           'admin css' => 'right_admin.css',
           'regions' => array(
                      'xinwen' => t('xinwen'),
                      'tuijian' => t('tuijian'),
                      'luntan' => t('luntan'),
                      'zhuanjia' => t('zhuanjia'),
            ),
);

